openapi: 3.0.4
info:
  title: Card Generator
  description: >-
    Card Generator is a simple tool for generating test/sample card numbers. It
    returns a list of card numbers for testing.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/cardgenerator:
    get:
      summary: Generate Card Numbers
      description: Generate a list of test card numbers
      operationId: cardgenerator
      parameters:
        - name: brand
          in: query
          schema:
            type: string
          required: true
          description: The brand of the card to generate
          example: visa
        - name: count
          in: query
          schema:
            type: integer
          required: false
          description: The number of test card numbers to generate
          example: 5
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  brand: visa
                  count: 5
                  cards:
                    - cvv: 175
                      issuer: SOUTHEAST F.C.U.
                      id: 0faca124-9a33-4ac6-a3df-8bf103025779
                      number: '4750377207233152'
                      expiration: 12/2030
                      brand: visa
                      number_alt:
                        masked: '************3152'
                        unmasked: 4750 3772 0723 3152
                        last4: '3152'
                    - cvv: 129
                      issuer: U.S. BANK, N.A.
                      id: 0d074efe-69e2-4e30-b49a-4cead1ea8411
                      number: '4431387818727358'
                      expiration: 12/2030
                      brand: visa
                      number_alt:
                        masked: '************7358'
                        unmasked: 4431 3878 1872 7358
                        last4: '7358'
                    - cvv: 249
                      issuer: AUGUSTA VAH F.C.U.
                      id: 2f01f458-7422-400e-bbcf-41364564193b
                      number: '4425919427248836'
                      expiration: 12/2030
                      brand: visa
                      number_alt:
                        masked: '************8836'
                        unmasked: 4425 9194 2724 8836
                        last4: '8836'
                    - cvv: 892
                      issuer: CITIZENS SECURITY BANK AND TRUST COMPANY
                      id: d311e9d0-f410-4f75-a21f-f14125c88cbb
                      number: '4127737519045634'
                      expiration: 12/2030
                      brand: visa
                      number_alt:
                        masked: '************5634'
                        unmasked: 4127 7375 1904 5634
                        last4: '5634'
                    - cvv: 524
                      issuer: CREDIT LIBANAIS S.A.L.
                      id: 64113f4d-c625-43d2-9d82-04f220c9e26f
                      number: '4741441509416816'
                      expiration: 12/2030
                      brand: visa
                      number_alt:
                        masked: '************6816'
                        unmasked: 4741 4415 0941 6816
                        last4: '6816'
                  owner:
                    name: Benny Swaniawski
                    address:
                      street: 007 Nelson Mountains
                      city: Margueriteton
                      state: Washington
                      zipCode: 39956-7950
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
