openapi: 3.0.4
info:
  title: Card Generator
  description: Card Generator is a simple tool for generating test/sample card numbers. It returns a list of card numbers for testing.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/cardgenerator:
    get:
      summary: Generate Card Numbers
      description: Card Generator is a simple tool for generating test/sample card numbers. It returns a list of card numbers for testing.
      operationId: cardgenerator
      parameters:
      - name: brand
        default: visa
        in: query
        schema:
          type: string
        required: true
        description: The brand of the card (e.g., visa, mastercard, amex, discover)
        example: visa
      - name: count
        default: '1'
        in: query
        schema:
          type: integer
        required: false
        description: The number of test card numbers to generate
        example: '5'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  brand: visa
                  count: 5
                  cards:
                  - cvv: 798
                    issuer: BANCO BILBAO VIZCAYA ARGENTARIA PARAGUAY, S.A.
                    id: c5805305-62df-43d8-bdfd-ac72b459cc64
                    number: '4236228422790803'
                    expiration: 05/2030
                    brand: visa
                    number_alt:
                      masked: '************0803'
                      unmasked: 4236 2284 2279 0803
                      last4: '0803'
                  - cvv: 284
                    issuer: IDBI BANK, LTD.
                    id: 6a9d0686-6390-40d3-81a9-83cb7da1e1e1
                    number: '4581393917480061'
                    expiration: 05/2030
                    brand: visa
                    number_alt:
                      masked: '************0061'
                      unmasked: 4581 3939 1748 0061
                      last4: '0061'
                  - cvv: 184
                    issuer: CREDIT SAISON CO., LTD.
                    id: 97e9a5cb-0bd1-46d5-b486-61caf7692155
                    number: '4541313270704781'
                    expiration: 05/2030
                    brand: visa
                    number_alt:
                      masked: '************4781'
                      unmasked: 4541 3132 7070 4781
                      last4: '4781'
                  - cvv: 649
                    issuer: CARD SERVICES FOR CREDIT UNIONS, INC.
                    id: 013f5e59-5c1a-4c92-a2a7-171384de2416
                    number: '4148851836478785'
                    expiration: 05/2030
                    brand: visa
                    number_alt:
                      masked: '************8785'
                      unmasked: 4148 8518 3647 8785
                      last4: '8785'
                  - cvv: 161
                    issuer: JPMORGAN CHASE BANK, N.A.
                    id: d4cf0704-7c48-4221-bcae-53c676261487
                    number: '4867963822584424'
                    expiration: 05/2030
                    brand: visa
                    number_alt:
                      masked: '************4424'
                      unmasked: 4867 9638 2258 4424
                      last4: '4424'
                  owner:
                    name: Herman Gulgowski
                    address:
                      street: 3659 Konopelski Coves
                      city: Schmittburgh
                      state: Utah
                      zipCode: 01681-6561
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
