name: apiverve_cardgenerator
description: Card Generator is a simple tool for generating test/sample card numbers. It returns a list of card numbers for testing.
version: 1.1.14
homepage: https://apiverve.com/marketplace/cardgenerator?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/cardgenerator-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
